default_install_hook_types = ["pre-commit", "pre-push"]

[[repos]]
repo = "local"

[[repos.hooks]]
id = "ruff-format"
name = "ruff format"
language = "system"
entry = "uv run --locked ruff format"
types = ["python"]
stages = ["pre-commit"]
require_serial = true
priority = 0

[[repos.hooks]]
id = "ruff-check"
name = "ruff check --fix"
language = "system"
entry = "uv run --locked ruff check --fix"
types = ["python"]
stages = ["pre-commit"]
require_serial = true
priority = 10
