import vapoursynth as vs

from typing import Optional, Any


def DPIR(clip: vs.VideoNode, strength: Optional[float] = None, task: str = 'denoise',
         device_type: str = 'cuda', device_index: int = 0) -> vs.VideoNode: ...
def frame_to_tensor(f: vs.VideoFrame) -> Any: ...
def tensor_to_frame(t: Any, f: vs.VideoFrame) -> vs.VideoFrame: ...
