import torch
import vapoursynth as vs

def DPIR(clip: vs.VideoNode, strength: float=..., task: str=..., device_type: str=..., device_index: int=...) -> vs.VideoNode: ...
def frame_to_tensor(f: vs.VideoFrame) -> torch.Tensor: ...
def tensor_to_frame(t: torch.Tensor, f: vs.VideoFrame) -> vs.VideoFrame: ...
