from typing import Any

def test_mode(model: Any, L: Any, mode: int = ..., refield: int = ..., min_size: int = ..., sf: int = ..., modulo: int = ...): ...
def test(model: Any, L: Any): ...
def test_pad(model: Any, L: Any, modulo: int = ...): ...
def test_split_fn(model: Any, L: Any, refield: int = ..., min_size: int = ..., sf: int = ..., modulo: int = ...): ...
def test_onesplit(model: Any, L: Any, refield: int = ..., min_size: int = ..., sf: int = ..., modulo: int = ...): ...
def test_split(model: Any, L: Any, refield: int = ..., min_size: int = ..., sf: int = ..., modulo: int = ...): ...
def test_x8(model: Any, L: Any, modulo: int = ...): ...
def test_split_x8(model: Any, L: Any, refield: int = ..., min_size: int = ..., sf: int = ..., modulo: int = ...): ...
def print_model(model: Any) -> None: ...
def print_params(model: Any) -> None: ...
def info_model(model: Any): ...
def info_params(model: Any): ...
def describe_model(model: Any): ...
def describe_params(model: Any): ...
