# flake8: noqa

import typing

import vapoursynth as vs


def kirsch(src: vs.VideoNode) -> vs.VideoNode: ...
def retinex_edgemask(src: vs.VideoNode, sigma: typing.Union[float, typing.Sequence[float]] = 1.0) -> vs.VideoNode: ...
def squaremask(clip: vs.VideoNode, width: int, height: int, offset_x: int, offset_y: int) -> vs.VideoNode: ...
def hardsubmask_fades(clip: vs.VideoNode, ref: vs.VideoNode, expand_n: int = 8, highpass: int = 5000) -> vs.VideoNode: ...
def hardsubmask(clip: vs.VideoNode, ref: vs.VideoNode, expand_n: typing.Optional[int] = None) -> vs.VideoNode: ...
def crossfade(clipa: vs.VideoNode, clipb: vs.VideoNode, duration: int) -> vs.VideoNode: ...
