from enum import IntEnum

class SectorOffset(IntEnum):
    DVDVIDEO_VTS: int
    LAST_SECTOR_TITLE_SET: int
    LAST_SECTOR_IFO: int
    VERSION_NB: int
    VTS_CATEGORY: int
    VTS_MAT_END_BYTE: int
    START_VECTOR_MENU_VOB: int
    START_VECTOR_TITLE_VOB: int
    SECTOR_POINTER_VTS_PTT_SRPT: int
    SECTOR_POINTER_VTS_PGCI: int
    SECTOR_POINTER_VTSM_PGCI_UT: int
    SECTOR_POINTER_VTS_TMAPTI: int
    SECTOR_POINTER_VTSM_C_ADT: int
    SECTOR_POINTER_VTSM_VOBU_ADMAP: int
    SECTOR_POINTER_VTS_C_ADT: int
    SECTOR_POINTER_VTS_VOBU_ADMAP: int
    VID_ATT_VTSM_VOBS: int
    NB_AUDIOS_VTSM_VOBS: int
    AUD_ATT_VTSM_VOBS: int
    NB_SUBPIC_STREAMS_VTSM_VOBS: int
    SUBPIC_ATT_VTSM_VOBS: int
    RESERVED: int
