name: Lint Python code with Ruff & mypy

on:
  push:
    branches:
      - master
    paths:
      - "**.py"
      - "pyproject.toml"
  pull_request:
    paths:
      - "**.py"
      - "pyproject.toml"
  workflow_dispatch:

permissions:
  contents: read

env:
  LVSFUNC_PYTHON_VERSION: 3.14

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up uv
        uses: astral-sh/setup-uv@v8.1.0
        with:
          python-version: ${{ env.LVSFUNC_PYTHON_VERSION }}
          enable-cache: true

      - name: Install dependencies
        run: uv sync --locked

      - name: Run Ruff check
        id: ruff_check
        run: uv run --no-sync ruff check .

      - name: Run Ruff format
        id: ruff_format
        if: success() || (failure() && steps.ruff_check.conclusion == 'failure')
        run: uv run --no-sync ruff format --check --diff

      - name: Running mypy
        if: success() || (failure() && (steps.ruff_check.conclusion == 'failure' || steps.ruff_format.conclusion == 'failure'))
        run: uv run --no-sync mypy .

      - name: Post webhook for failure
        if: failure()
        uses: Jaded-Encoding-Thaumaturgy/discord-failure-notifier@v1
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
